name: Final_Build_System

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          npm install -g cordova
          cordova platform add android@13.0.0
          
          # تثبيت الإضافات
          cordova plugin add cordova-plugin-android-permissions
          cordova plugin add cordova-plugin-device
          cordova plugin add cordova-plugin-androidx-adapter
          cordova plugin add cordova-open-native-settings
          cordova plugin add com-darryncampbell-cordova-plugin-intent
          
          cordova prepare android
          
          # توقيع التطبيق
          keytool -genkey -v -keystore release.jks -alias safety_key -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Zakaria" -deststoretype pkcs12

          cordova build android --release -- --packageType=apk
          
          mkdir output
          cp platforms/android/app/build/outputs/apk/release/*.apk ./output/Safety_Call_Final.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Final-App-Build
          path: output/
